apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: smartproperty
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog:v1.0.1
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: web
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: smartproperty
spec:
  selector:
    app: mailhog
  ports:
    - port: 1025
      targetPort: 1025
      name: smtp
    - port: 8025
      targetPort: 8025
      name: web
