apiVersion: v1
kind: Secret
metadata:
  name: smartproperty-secrets
  namespace: smartproperty
type: Opaque
stringData:
  # MongoDB
  MONGODB_USERNAME: smartproperty_user
  MONGODB_PASSWORD: smartproperty_pass_2024
  MONGODB_URI: mongodb://smartproperty_user:smartproperty_pass_2024@mongodb:27017/smartproperty?authSource=admin

  # Redis
  REDIS_PASSWORD: redis_dev_password_2024
  REDIS_URL: redis://:redis_dev_password_2024@redis:6379

  # JWT
  JWT_SECRET: smartproperty_jwt_secret_dev_2024_change_in_prod
  JWT_REFRESH_SECRET: smartproperty_refresh_secret_dev_2024

  # MinIO
  MINIO_ACCESS_KEY: smartproperty_minio
  MINIO_SECRET_KEY: smartproperty_minio_secret_2024
  MINIO_ROOT_USER: smartproperty_minio
  MINIO_ROOT_PASSWORD: smartproperty_minio_secret_2024

  # Google OAuth
  GOOGLE_CLIENT_ID: "536589803506-2m576m65ekecq64o4ggvfov1iig9ilpc.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: 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

  # Facebook OAuth
  FACEBOOK_CLIENT_ID: "2169585796854877"
  FACEBOOK_CLIENT_SECRET: 1892d0d8d71e57c1df7122711595fae2

  # VAPID
  VAPID_PUBLIC_KEY: BKBMsOwRgWugdWBo4CscoRXaYqHv6wzMyPbk-8wi00KwcY3pzCp9YjeqjopofefTGPMQ9n3b2OzXpZwkam-xPyw
  VAPID_PRIVATE_KEY: wKyDDYjdGnA-YpC-IFYZZO5IY2lYA-zT8TKps0EZnHo
